workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - cd mobile
      - flutter pub get
      - flutter build ipa --release

    artifacts:
      - mobile/build/ios/ipa/*.ipa